### ISSUE TITLE
StorageForbiddenException: You are forbidden to do this.

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#215]
### Actual Behavior

I get an error 

`StorageForbiddenException: You are forbidden to do this.`

from this line:

```
/opt/conda/envs/python2/lib/python2.7/site-packages/hbp_validation_framework/datastores.pyc in _download_data_content(self, remote_path)
    122             remote_path = remote_path[len("collab:/"):]
    123 
--> 124         entity = self.doc_client.get_entity_by_query(path=remote_path)
    125         if entity["entity_type"] == 'file':
    126             etag, content = self.doc_client.download_file_content(entity["uuid"])
```

when it is trying to download the file

`/6351/test_observations/YJ150915_c67D1ch01D2ch23-c6.zip`

However, that file seems to reside on the Collab with ID 6351, to which I have no access as user 'adietz'. 

### Steps to reproduce the problem

See #213 

### Optional infrastructural data (user, platform, browser, environment, ...)

DEV

**Comment by appukuttan-shailesh** [comment]
Thanks for identifying this. That indeed is a problem, but fortunately can be quickly fixed. I will move the reference data to a 'public' collab and update you here.

**Comment by appukuttan-shailesh** [comment]
Done. Could you test again? Thanks.

**Comment by alex4200** [comment]
@appukuttan-shailesh : Thanks for the quick fix, but there seem to another try to upload files to the collab with the ID 6351. It happens according to the following backtrace: 

```
  <ipython-input-6-208b12219350>(21)<module>()
     19     cell_model.params = hall_of_fame[hof_index]
     20 
---> 21     result_id = utils.run_test(hbp_username=HBP_USERNAME, environment="production", model=cell_model, test_alias="basalg_" + cell_type, test_version="1.0", cell_type=cell_type, register_result=True, client_obj=testLibrary, junction_potential=junction_potential, use_cache=True)
     22     result_uuids.append(result_id)
     23 print("The results can be viewed in the HBP Validation Framework app.")

  /opt/conda/envs/python2/lib/python2.7/site-packages/hbp_validation_framework/utils.py(240)run_test()
    238                                          auth=test_library.auth)
    239 
--> 240         response = test_library.register_result(test_result=score, data_store=collab_storage)
    241         # response = test_library.register_result(test_result=score)
    242         if 'model_instance_uuid' in locals():   # if this was set here, then the original model didn't specify it

> /opt/conda/envs/python2/lib/python2.7/site-packages/hbp_validation_framework/__init__.py(1225)register_result()
   1223                         fp.write("This validation test did not produce any additional data")
   1224                 files_to_upload = ["related_data.txt"]
-> 1225             results_storage = data_store.upload_data(files_to_upload)
   1226         else:
   1227             results_storage = ""

  /opt/conda/envs/python2/lib/python2.7/site-packages/hbp_validation_framework/datastores.py(71)upload_data()
     69             self.authorize(self._auth)
     70         projects_in_collab = self.doc_client.list_projects(collab_id=self.collab_id,
---> 71                                                            access='write')["results"]
     72         assert len(projects_in_collab) == 1
     73         project_id = projects_in_collab[0]["uuid"]
```

**Comment by appukuttan-shailesh** [comment]
Ah... I missed that one. The problem was that in cell #4 when we were registering a new model, the default value had been set to app_id=49879 which is inside a private collab (for the Basal Ganglia team). I have now changed the default to a publicly accessible version (671794). Do let me know if this works. Thanks.

**Comment by alex4200** [comment]
I still get the same error, although I seem to be able to access all the pages (i.e. https://collab.humanbrainproject.eu/#/collab/8123/nav/67179) . Below is the complete backtrace. 

I tried this twice(!), but saw the same error again. 

The offending line seems to be in datastores.py:

113                 child = self.doc_client.create_folder(folder_name, parent=parent)['uuid']

with folder_name = 'validation_results' and parent=u'6fa68dac-2e07-42fe-a8b7-fa43aa784839'.

I suggest to use a different email address in order to invite yourself as a different user (click on your little image, then go to 'Invite User'). That way you can test the use case as some other user...


```
Total available 'Hall of Fame' parameter sets = 10
Note: validation of each parameter set takes around 20 mins; for testing specify a single parameter set.
Enter the parameter set of interest: 0 - 9
Example inputs: 0, 4, [0,4,8,9], all
4
----------------------------------------------
('Model name: ', 'CellModel')
('Model type: ', <class 'basalunit.utils.CellModel'>)
----------------------------------------------
----------------------------------------------
('Test name: ', 'Basal Ganglia - Somatic Features')
('Test type: ', <class 'basalunit.tests.test_eFELFeaturesTest.eFELfeaturesTest'>)
----------------------------------------------
Note: no cached data for this model specification (hash)!
----------------------------------------------
('Score: ', 9.767497977577136)
Output files: 
/tmp/msn_d1_all-6-20170524/validation_results/efel_feat/msn_d1_all-6-20170524_hof_4/20180302-134211/model_exp_traces.pdf
/tmp/msn_d1_all-6-20170524/validation_results/efel_feat/msn_d1_all-6-20170524_hof_4/20180302-134211/hof_params.json
/tmp/msn_d1_all-6-20170524/validation_results/efel_feat/msn_d1_all-6-20170524_hof_4/20180302-134211/score_summary.txt
/tmp/msn_d1_all-6-20170524/validation_results/efel_feat/msn_d1_all-6-20170524_hof_4/20180302-134211/json_score_summary.json
/tmp/msn_d1_all-6-20170524/validation_results/efel_feat/msn_d1_all-6-20170524_hof_4/20180302-134211/relative_errors.pdf
/tmp/msn_d1_all-6-20170524/validation_results/efel_feat/msn_d1_all-6-20170524_hof_4/20180302-134211/absolute_errors.pdf
----------------------------------------------

StorageForbiddenExceptionTraceback (most recent call last)
<ipython-input-8-208b12219350> in <module>()
     19     cell_model.params = hall_of_fame[hof_index]
     20 
---> 21     result_id = utils.run_test(hbp_username=HBP_USERNAME, environment="production", model=cell_model, test_alias="basalg_" + cell_type, test_version="1.0", cell_type=cell_type, register_result=True, client_obj=testLibrary, junction_potential=junction_potential, use_cache=True)
     22     result_uuids.append(result_id)
     23 print("The results can be viewed in the HBP Validation Framework app.")

/opt/conda/envs/python2/lib/python2.7/site-packages/hbp_validation_framework/utils.pyc in run_test(hbp_username, environment, model, test_instance_id, test_id, test_alias, test_version, storage_collab_id, register_result, model_metadata, client_obj, **test_kwargs)
    238                                          auth=test_library.auth)
    239 
--> 240         response = test_library.register_result(test_result=score, data_store=collab_storage)
    241         # response = test_library.register_result(test_result=score)
    242         if 'model_instance_uuid' in locals():   # if this was set here, then the original model didn't specify it

/opt/conda/envs/python2/lib/python2.7/site-packages/hbp_validation_framework/__init__.pyc in register_result(self, test_result, data_store, project)
   1223                         fp.write("This validation test did not produce any additional data")
   1224                 files_to_upload = ["related_data.txt"]
-> 1225             results_storage = data_store.upload_data(files_to_upload)
   1226         else:
   1227             results_storage = ""

/opt/conda/envs/python2/lib/python2.7/site-packages/hbp_validation_framework/datastores.pyc in upload_data(self, file_paths)
     72         assert len(projects_in_collab) == 1
     73         project_id = projects_in_collab[0]["uuid"]
---> 74         base_folder_id = self._make_folders(self.base_folder, parent=project_id)
     75 
     76         if len(file_paths) > 1:

/opt/conda/envs/python2/lib/python2.7/site-packages/hbp_validation_framework/datastores.pyc in _make_folders(self, folder_path, parent)
    111                     break
    112             if not folder_exists:
--> 113                 child = self.doc_client.create_folder(folder_name, parent=parent)['uuid']
    114             parent = child
    115         return child

/opt/conda/envs/python2/lib/python2.7/site-packages/hbp_service_client/storage_service/api.pyc in create_folder(self, name, parent)
    618         return self._authenticated_request \
    619             .to_endpoint('folder/') \
--> 620             .with_json_body(self._prep_params(locals())) \
    621             .return_body() \
    622             .post()

/opt/conda/envs/python2/lib/python2.7/site-packages/hbp_service_client/request/request_builder.pyc in post(self)
    222             Any exception parametrized with the `throw` method
    223         '''
--> 224         return self.__send('POST')
    225 
    226     def delete(self):

/opt/conda/envs/python2/lib/python2.7/site-packages/hbp_service_client/request/request_builder.pyc in __send(self, method)
    258         )
    259 
--> 260         self.__throw_if_necessary(response, self._throws)
    261 
    262         if self._return_body:

/opt/conda/envs/python2/lib/python2.7/site-packages/hbp_service_client/request/request_builder.pyc in __throw_if_necessary(response, throws)
    270             args = should_throw(response)
    271             if args is not None:
--> 272                 raise exception_class(args)
    273 
    274     @staticmethod

StorageForbiddenException: You are forbidden to do this.
```

**Comment by appukuttan-shailesh** [comment]
Sure, will check with another account. p.s. do you know if there is any way to reset an account's collab environment? I already have a 'test' account. But I have used it in the past, so it won't be "starting afresh".

**Comment by appukuttan-shailesh** [comment]
I have identified the problem. I was under the impression that if a Collab is public, then anyone can access it AND also be able to create directories in its storage. It turns out that the latter isn't true. Only if a user is added to the 'Team' of a Collab (even public) can they perform actions in the storage.

Will change the target Collab to the one in which the UseCase was added (as opposed to a default constant value).

**Comment by alex4200** [comment]
@appukuttan-shailesh : Have you done the changes already? Or are you about to do them...?

**Comment by appukuttan-shailesh** [comment]
Almost done..... will test and verify at my end first. Shall update you soon.

**Comment by appukuttan-shailesh** [comment]
This looks ready. Worked with my testing account. You can have a go now.

**Comment by alex4200** [comment]
Works now, thanks
