### ISSUE TITLE
Error for analysis in use case "Rebuild an existing single hippocampal cell model"

### ISSUE THREAD

**Issue by alex4200** [cnr-ibf-pa/hbp-bsp-issues#32]
### Expected behavior

I am able to view the analysis from the Storage.

### Actual Behavior

I get an error because some directories do not seem to exist in a folder (directory 'OUTPUTBPOPT' and subfolder; see function runanalysis2. Actual error:

```
OSError                                   Traceback (most recent call last)
<ipython-input-5-d958dec3b164> in runanalysis2(_)
    174     else:
    175         os.chdir(w3.value)
--> 176         os.chdir('OUTPUTBPOPT')
    177         for files in os.listdir('.'):
    178             if os.path.isdir(files):
```

### Steps to reproduce the problem

Run the complete analysis, and in the last notebook 'BluePyOpt Analysis' select 'Storage' and wait until the graph shows up and the button 'View analysis' becomes clickable. Then click on this button.
Closely related to issue #26 

### Optional infrastructural data (user, platform, browser, environment, ...)

FF

![selection_045](https://user-images.githubusercontent.com/12729291/31600356-666cae64-b256-11e7-9e4e-6b977078e425.png)

**Comment by clupascu** [comment]
Can you add me as a team member of this collab? I need to take a look at the storage.
Thanks.

**Comment by alex4200** [comment]
@clupascu : Added you; its collab "Retest27a "

**Comment by clupascu** [comment]
Ok. There is nothing actually to analyze in the storage. I will modify the code in order to give some feedback in this case.

**Comment by clupascu** [comment]
I fixed this. Can you please test again?
Thanks.

**Comment by alex4200** [comment]
@clupascu : So now I get a popup saying "No pkl file in the checkpoints folder". I have no idea what it means. I just did the calculations, and now I have no results? Nothing to analyse? I am a bit confused...

**Comment by clupascu** [comment]
So in the storage of the collab you shared with me (Retest27a) you had no directory called BluePyOptOne, hence no optimization was runned before in this collab. Hence when you click on Storage no folder is displayed and no morphology is displayed. When you click on View analysis button you are supposed to get a popup saying "No optimizations to analyse" as in fact there is no optimization to analyse in the storage.

**Comment by alex4200** [comment]
@clupascu : Did you remove the notebook for "Analysis" in the collab "Retest27a"? Seems to have vanished...

**Comment by alex4200** [comment]
@clupascu I still do not understand. Why do I run the calculation (the one started in "BluePyOpt One")? What is this calculation for? Where can I see the results? And why can I select "GitHub" optimizations? And what is an optimization? Maybe we should have a short skype call...

**Comment by clupascu** [comment]
I tested again this use case. I selected the first model Rat > Hippocampus > CA1 > interneuron >
bAC > 011017HP2. I clicked on Create zip file and then I setted number of nodes to 2, number of cores to 10 and runtime to 1. The job completed and inside the checkpoints folder I find the checkpoint.pkl file. Everything ended in less than 3 hours. My test collab is BSP_rebuild_06_11_2017_Carmen2. I added you as a team member. Can you please test again selecting the model and setting the parameters as suggested? Thanks.

**Comment by alex4200** [comment]
@clupascu: Investigation started in Collab "TestReb2"

**Comment by alex4200** [comment]
@clupascu : Finally I got a file in 'checkpoints'. Unfortunately, I got a 'server error' after having clicked on 'View Analysis'... I repeated it, but got the same error. 

I invited you to that collab.

**Comment by clupascu** [comment]
I get the same server error. It is an error caused by the pdf display. It happened in the past too. I think the collab update caused this error again. I will report it to the collab team.

**Comment by alex4200** [comment]
Thanks...

**Comment by alex4200** [comment]
Original problem solved, followup error in ticket #71
